<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Hostel_Management_System_Backend.DTO</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hostel-Management-System-Backend.Infrastructure\Hostel-Management-System-Backend.Infrastructure.csproj" />
    <ProjectReference Include="..\Hostel-Management-System-Backend.Services\Hostel-Management-System-Backend.Services.csproj" />
  </ItemGroup>

</Project>
